### ISSUE TITLE
Texts broken since moving to OpenData parsing for 15th

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/anpy#11]
- [x] pjl16-084 [explication: rapport 107 en HTML n'éxiste pas, avant]
- [x] pjl16-522
- [x] pjl16-585
- [x] pjl16-587
- [x] pjl17-036
- [x] pjl17-062
- [x] pjl17-105

**Comment by mdamien** [comment]
Fixed pjl16-084 with:

 - 9c9ca3f36dc24223f74b4388b5667a002e39a6f7
 - 8a65553655fdc033cf5821ca857b501ab03850b9
 - 54dd76cb401f637183e581d45c5da8c12ab81286

Fixed pjl16-522 with a fix in senapy: https://github.com/regardscitoyens/senapy/commit/cfa41c90a6e72d38bbe981b5b70e75620245bc19 ("//" in AN dosleg url on the senat side)
