### ISSUE TITLE
handle dossiers multi-legislature 14-15 with old 14th dossier redirected to dyn

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/anpy#16]
cf https://github.com/regardscitoyens/lawfactory_utils/commit/6df5aab20dd212e5218d4ed0f1c825738a9d94c8#commitcomment-29601949
It breaks parsing Confiance when using AN's dossier as entry point, which is not breaking since it does work when calling from Senate's dossier ID.

Although it does break previously working parsing for the two following texts:
- pjl16-432
- ppl16-362

In both cases, it results in:
- 1st lecture AN commission step duplicated with both urls to asp and pdf
- 1st lecture AN hemicycle step duplicated with url asp (wrongly declared as depot) and url pdf (properly announced as hemicycle)

**Comment by mdamien** [comment]
Problem solved for pjl16-432 and ppl16-362 but for confiance it's gonna be hard: It's not in the Open Data and the individual page was [not backed-up for the 14th legislature](https://raw.githubusercontent.com/regardscitoyens/archive-AN-doslegs/master/archive/14/dossiers/retablissement_confiance_action_publique.asp) (it's [backed up for the 15th legislature](retablissement_confiance_action_publique))

So, maybe the best is just to push for the AN to add the missing doslegs to the Open Data....
