### ISSUE TITLE
New open data page of all publications

### ISSUE THREAD

**Issue by David-Guillot** [regardscitoyens/anpy#26]
Hi there,

Just to let you know, in case you missed it, that French Assembly now provides an open data complete list of publications for a given day:

* Today: `http://www.assemblee-nationale.fr/dyn/opendata/list-publication/publication_j`
* Some past day: `http://www.assemblee-nationale.fr/dyn/opendata/list-publication/publication_j-{N}`
* A given date: `http://www.assemblee-nationale.fr/dyn/opendata/list-publication/publication_{YYYY-MM-DD}`

These pages expose a CSV of publication dates and texts and amendments URLs, linking to the new open data formats ([XML](http://www.assemblee-nationale.fr/dyn/opendata/AMANR5L15PO717460B3522P0D1N000107.xml) or [JSON](http://www.assemblee-nationale.fr/dyn/opendata/AMANR5L15PO717460B3522P0D1N000107.json) for amendments, [stable HTML](http://www.assemblee-nationale.fr/dyn/opendata/PIONANR5L15B0687.html) for texts).

More details in [their FAQ](http://data.assemblee-nationale.fr/foire-aux-questions).

I thought you might find this interesting.

**Comment by mdamien** [comment]
Interesting, thank you !

**Comment by David-Guillot** [comment]
Some more information about this: we've been notified this morning that the usual URL `http://www2.assemblee-nationale.fr/recherche/query_amendements` is now deprecated by French Assembly, and will be removed on December 21st. I hope they communicate with you as well as they do with us.

**Comment by mdamien** [comment]
Yup, got the mail too :)

Le jeu. 12 nov. 2020 à 12:31, David Guillot <notifications@github.com> a
écrit :

**Comment by mdamien** [comment]
Gonna send them a very simple mail: "Could you put the URL of the amendement in the amendement file ?" :smile: 

EDIT: (sorry for not-so-related comment, by my god how it's annoying to have to guess the url manually)

**Comment by boogheta** [comment]
@mdamien while it is a real pain for documents, for amendments it is not so bad, I do it very simply with just a sed command:
https://github.com/regardscitoyens/nosdeputes.fr/blob/master/batch/amendements/check_missing.sh#L19

edit: But it would definitely be better if they would put it in the data, so feel free to ask them!

**Comment by David-Guillot** [comment]
Cleaning up my Github. This seems to have been implemented for a while.
